export * from './app.component';
export * from './login/login.component';
export * from './logout/logout.component';
export * from './main/main.component';
export * from './main/centros/centros.component';
export * from './main/contactos/contactos.component';
export * from './main/entidades-fiscales/entidades-fiscales.component';
export * from './main/seguridad/seguridad.component';
export * from './main/dummy/dummy.component';